# This is a basic workflow to help you get started with Actions

name: Deploy Production Backend 

# Controls when the workflow will run
on:
  push:
    branches: [ "production" ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ secrets.DOCKER_TAG }}
      
      - name: Trigger deployment webhook
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"image":"${{ secrets.DOCKER_IMAGE_NAME }}","tag":"${{ secrets.DOCKER_TAG }}"}' \
            ${{ secrets.WEBHOOK_URL }}
