name: Deploy Production Backend

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy Firebase service account
        run: |
          cp ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PATH }} ./firebase-service-account.json

      - name: Build Docker image
        run: |
          docker build -t project-showcase-backend:latest .

      - name: Deploy new container
        run: |
          # Stop and remove existing container if running
          docker stop project-showcase-backend || true
          docker rm project-showcase-backend || true

          # Run new container
          docker run -d \
            --name project-showcase-backend \
            --restart unless-stopped \
            -p 8000:8000 \
            --env-file ${{ secrets.ENV_FILE_PATH }} \
            project-showcase-backend:latest
